### PR TITLE
Add Ace Editor

### PR DESCRIPTION
**Pull request by paavanb**
# Ace Code Editor
This PR uses the `react-ace` library for displaying and editing the metric code. It's a fully-featured code editor that supports theming and syntax highlighting, making it much easier to read and edit the code.

# New Algorithm
I edited the code to only use the 2016 House election results. I don't think the previous calculation was accurate, since it was averaging over several years and creating data for uncontested elections when none was available. Fortunately the 2016 House results have no uncontested elections, making the efficiency gap calculation straightforward and readable.

# Moved State Data
The state data was located at the bottom of the page, making it difficult to iterate on the algorithm. I moved it to the top, right under the algorithm section, inside an accordion so that it can be expanded if the user is curious.

# Prerequisites
I'll merge this after the "separate page" PR, since the editor behaves poorly with the modal.

### CODE REVIEW

**Comment by willcrumbley** [comment]
We should talk more about your edits to the default algorithm - I think what was there was consistent with the algorithm as described in the original paper.

**Comment by paavanb** [comment]
I decided to change it so that the algorithm was easier to understand and follow, since it wouldn't do any data munging and instead just be a straightforward application of the efficiency gap.

I noticed that it was finding uncontested house elections and replacing their results with the results of the presidential election. That was described in their paper? But then, the map claimed to be "as of 2016", which was inaccurate since it was averaging across several years.

**Comment by paavanb** [comment]
@willcrumbley  I found the section in the paper discussing different approaches for handling uncontested elections, so I'm fine with that. However, I don't think we should be averaging across several elections. The paper itself points out that " a plan’s efficiency gap in one election is a relatively weak predictor of its gap in the next election (coefficient = 0.23) ", which seems to suggest that averaging across several years would give us a skewed picture of what the efficiency gap is today.

If we only calculate the efficiency gap for 2016, we don't have to deal with uncontested elections and it makes the code read in a much simpler way; I want to avoid scaring people off with what looks like a complicated algorithm when the efficiency gap is actually incredibly simple.

**Comment by willcrumbley** [comment]
You're right - I just re-read the paper, and I'm not sure where I came up with the "average of the past 3 elections" part of the standard algorithm.  I do think we need to take into account the sensitivity testing that they include as part of their test of constitutionality, though - what are your thoughts on how we'd operationalize this?
"A word is in order too about the sensitivity testing we suggest
incorporating into the thresholds. We recommend the testing
because, as we have stressed, a plan’s efficiency gap may
change substantially from one election to the next. It makes little
sense to say that a plan is a presumptively unlawful gerrymander
in one election, if in the next its efficiency gap could
switch to favor the opposing party. To take into account this volatility,
we propose treating a plan as presumptively invalid only
if its gap exceeds the threshold we have identified and the gap is
unlikely to hit zero over the plan’s lifetime. To determine the
odds of the gap hitting zero, we suggest shifting the actual election
results by percentages derived from historical data—up to
7.5 percent in each direction for congressional plans and up to
5.5 percent for state house plans—and then calculating the gap
for each vote share shift."

Why don't we remove the algorithm change from this PR then discuss a separate change that would allow us to include the sensitivity analysis in the calculation or display of results?

**Pull request closed without merging**
